### ISSUE TITLE
No Sets command found

### ISSUE THREAD

**Issue by macbikegeek** [Canna71/obsidian-sets#22] opened 2024-02-13 23:32 UTC
I assume that the Sets command should show up with Cmd-P or /Sets, but there are no Sets commands. Obsidian 1.5.5

Thanks for any help.

**Comment by Canna71** [comment] 2024-02-15 11:32
Something in the newest Obsidian release broke it, I will have a look ASAP.

**Comment by macbikegeek** [comment] 2024-02-15 16:30
Thanks so much!

**Comment by Canna71** [comment] 2024-02-15 17:35
Fixed in 1.0.14 it should also work with previous versions

**Comment by Canna71** [comment] 2024-02-15 17:50
There is still something broken... it looks like Obsidian 1.5.5 changed a bit of things...

**Comment by macbikegeek** [comment] 2024-02-15 18:32
It's working better - I get the commands in the Command Palette. When I create a Type note, it keeps putting created and updated timestamp lines in the note before the placeholder for the Type properties. Interestingly, this also happened in testing the Tasks Calendar plugin with someone else who was trying to fix it - the note with the calendar did the same thing.

**Comment by Canna71** [comment] 2024-02-15 20:29
Yes, the commands are now fixed (Obsidian changed something internally and it broke this plugin). 
Unfortunately there is a regression in Obsidian 1.5.5 which breaks the frontmatter processing but should be fixed in next build:

https://forum.obsidian.md/t/automatically-update-last-modified-date-in-note/51776/64

**Comment by macbikegeek** [comment] 2024-02-15 21:43
Thanks! I'll read the Sets documentation in the meantime and let you know how it goes once Obsidian is updated. :-)

**Comment by Canna71** [comment] 2024-02-17 10:57
Obsidian 1.5.6 was published (at least for Catalyst) and restored all functionalities.

**Closed by Canna71** 2024-02-17 10:57 UTC

**Comment by macbikegeek** [comment] 2024-02-17 16:47
Confirmed that the properties problem is fixed by 1.5.6. Now I have to go learn how to use Sets! Thanks for the quick responses! 🙏
